__global__ void vecAdd(DataType *in1, DataType *in2, DataType *out, int len) {
  //@@ Insert code to implement vector addition here
}

int main(int argc, char **argv) {  
 …
  //@@ Insert code below to allocate Host memory for input and output
 …
  //@@ Insert code to below to Copy memory to the GPU here
 …
  //@@ Launch the GPU Kernel here
 …
  //@@ Copy the GPU memory back to the CPU here
 …
}